# Generated by Django 2.2.2 on 2019-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
